### ISSUE TITLE
As a user,  I want to register so I can log in.

### ISSUE THREAD

**Issue by alexacarleo** [mshaffer9/ReelMarkets#1]
**Story/Task Details:**
- [x] Design Registration page

- [x] Create user map with information (username, email, gender, birthday, account type, password, and in-app currency)

**Acceptance Test Scenario:**
Given: An unregistered user
When: The user enters a unique username, valid email address, valid password, and age over 13
Then: The system creates a new user 

Given: An unregistered user
When: The user enters a non-unique username, or invalid password, or an invalid password, or an age less than 13
Then: The systems produces an error message

**Done Done Criteria:**

- [x] Team has approved UI design

- [x] UI elements exported and given to team

- [x] Code is merged with master

- [x] Acceptance scenarios are passing.

**Comment by alexacarleo** [comment]
![login button](https://cloud.githubusercontent.com/assets/3826457/22314658/6e4a6932-e330-11e6-9200-691defdad6b5.png)
![login shadow box](https://cloud.githubusercontent.com/assets/3826457/22314659/6e56effe-e330-11e6-9fe4-4d7daee0a6f2.png)

**Comment by alexacarleo** [comment]
![login button](https://cloud.githubusercontent.com/assets/3826457/22314724/aeb5c16a-e330-11e6-91c4-b9864ab57ad9.png)
![register shadow box](https://cloud.githubusercontent.com/assets/3826457/22314725/aec0c312-e330-11e6-9787-877664a84e91.png)

**Comment by mshaffer9** [comment]
TODO: fix fields to only accept proper types of input (numerical DOB, gender options, etc). Right now they are all strings.

**Comment by alexacarleo** [comment]
Background color: e6e6e6

**Comment by alexacarleo** [comment]
![envelope](https://cloud.githubusercontent.com/assets/3826457/22390987/715a9d6c-e4bc-11e6-8e8b-c087ad1d8ad3.png)
![lock](https://cloud.githubusercontent.com/assets/3826457/22390989/715b3826-e4bc-11e6-8360-99d3febaee49.png)
![person icon](https://cloud.githubusercontent.com/assets/3826457/22390988/715b3272-e4bc-11e6-8d08-1eeacf8dd013.png)
![lock with check](https://cloud.githubusercontent.com/assets/3826457/22391024/aaaee320-e4bc-11e6-865a-cc2036f41559.png)

**Comment by vgupta61** [comment]
Haven't implemented age over 13/ valid date of birth and valid email. Current input fields need to be improved - we should implement a calendar for dates, dropdown for gender, etc.
